/* ============================================================
   SKILLS CONSTELLATION — ALL CONTENT LIVES HERE.
   Edit this file to change anything on the map; no code changes needed.

   categories[].skills: [ "Name", weight, [evidenceIds] ]
     weight 3 = signature strength (large star, opens proof)
     weight 2 = proven in practice (medium star, opens proof)
     weight 1 = working skill (small star, part of the field)
   evidence: id -> { t: title, b: body, s: source }
   ============================================================ */
window.MAP_DATA = {
  person: {
    name: "Ryan Hance",
    title: "A Complete Map of Practice",
    sub: "Every skill in the set — untailored, unabridged. Bright stars carry the story behind them.",
  },
  evidence: {
    blueprint20k: { t: "20,000-point global service blueprint", b: "Mapped the Farmer persona inside a global enterprise service blueprint — 20,000+ data points across five countries and hundreds of teams — and led its migration from Miro to TheyDo.", s: "Bayer Crop Science · 2022–23" },
    journey2250: { t: "27-team global journey program", b: "Facilitated a journey mapping effort across NA, EMEA, and APAC that produced 2,250 journey points across 27 teams — driving material reductions in environmental-toxin risk and gains in workplace safety within two quarters.", s: "Bayer Crop Science · 2022–23" },
    siterebuild: { t: "UX Lead, end-to-end customer site rebuild", b: "Led the Farmer experience across pre-auth marketing, product, and agronomy surfaces and the post-auth Grower Portal. Aligning hundreds of technical stories, research discoveries, and business goals to user needs drove a 35% increase in product and service opportunities across the NA and LATAM builds.", s: "Bayer Crop Science · 2022–23" },
    udp: { t: "Universal Design Principles", b: "Authored the design principles adopted across every platform under the Head of Design for the $27B Crop Science division.", s: "Bayer Crop Science · 2022–23" },
    workshops: { t: "Hundreds of workshops, 5 to 150 people", b: "Facilitated hundreds of design-thinking workshops for diverse teams, maturing design practice and a culture of user-centered innovation company-wide. Selected by Miro as the single Enterprise Advocate for the ~100,000-person company.", s: "Bayer Crop Science · 2022–23" },
    cdp: { t: "Enterprise CDP vendor selection", b: "Drove the research and strategy that anchored the company's selection of its enterprise Customer Data Platform vendor, then structured the team composition for integrating and enhancing user experience and business insights after selection.", s: "Bayer Crop Science · 2022–23" },
    uat: { t: "UAT across the NA user base", b: "Led User Acceptance Testing for the end-to-end customer site rebuild across the North American user base.", s: "Bayer Crop Science · 2022–23" },
    adoption: { t: "2% → 26% AI adoption in two months", b: "Authored the company's AI Strategy Playbook and led its global dissemination — internal AI-platform adoption rose from 2% to 26% in two months, reaching thousands of users across business, engineering, design, and HR in 20+ languages in a single quarter.", s: "Bayer Crop Science · 2023" },
    personas: { t: "Agentic persona service, pre-Copilot", b: "Pioneered AI personas across company-wide platforms before commercial AI integrations existed for the collaboration stack: high-fidelity representations of unreachable users in under 15 minutes, validated above 80% accuracy by veteran SMEs — significantly reducing UAT failures and raising design maturity across the organization.", s: "Bayer Crop Science · 2023" },
    llm: { t: "Internal LLM platform strategy", b: "Provided strategic input on the build of the company's internal LLM platform, impacting design and product decisions and leading user testing.", s: "Bayer Crop Science · 2023" },
    teamsagent: { t: "Agentic AI in Teams, before Copilot", b: "Hand-built agentic AI into a Fortune 500's Microsoft Teams experience before Copilot or buildable GPTs existed.", s: "Bayer Crop Science · 2023" },
    prompttemplate: { t: "The template that unlocked genAI", b: "Developed the prompt-engineering template that enabled internal stakeholders around the world to leverage generative AI for the first time.", s: "Bayer Crop Science · 2023" },
    scrumboard: { t: "A scrum board from nothing", b: "Built out and wrote all stories for a legacy Operations Platform product team that had no user stories or change tracking.", s: "Bayer Crop Science · 2022–23" },
    dryland450: { t: "A startup's entire operating system", b: "Built a 450-data-point enterprise-level service blueprint and the company-wide playbook library it produced — lifting efficiency 80%, becoming the strategic information architecture for executive decision-making, and removing the CEO from lower-level conversations.", s: "Dryland Revival · 2022–25" },
    eraf: { t: "ERAF map, 100+ interaction points", b: "Ethnographic research revealed that 'bad communication' complaints were really a misunderstanding of the larger business model. The resulting map helped siloed employees see their role in the whole system — and retained a high percentage of employees who had planned to leave.", s: "Dryland Revival · 2022–25" },
    drylandorg: { t: "2× revenue, 4× headcount in three months", b: "Redesigned the organizational structure to detach the CEO from daily hands-on work so he could focus on sales, design, and leadership. Revenue doubled and headcount quadrupled in three months; the business reached a profitable exit via sale in 2025.", s: "Dryland Revival · 2022–25" },
    drylandhiring: { t: "3 → 15 in a season; a 100%-retention field test", b: "Built and ran the hiring funnel across three candidate markets — hundreds of first-round interviews, 30–40 hires across seasons, and a paid multi-day field test that produced 100% season-long retention of everyone who completed it.", s: "Dryland Revival · 2022–25" },
    pmsystem: { t: "A PM system built end-to-end, twice", b: "Designed the automations and information architecture of the project-management system — built end-to-end in ClickUp, then rebuilt end-to-end in Monday.com when the field team's mobile UX demanded it.", s: "Dryland Revival · 2022–25" },
    franchise: { t: "Nationwide franchise restructuring", b: "Led a counseling franchise through multi-state restructuring — ethnographic interviews with corporate and franchisees, comparative org charts, and the Franchise Criteria Canvas that streamlined corporate decisions on new franchisees — reorganizing headquarters without a single layoff.", s: "AGS Consulting · 2024–present" },
    km: { t: "AI-native knowledge management", b: "Building tool-agnostic knowledge management systems for creative and operational teams, architected for both human and agent ease of retrieval — built across multiple technologies and technological eras, especially skilled in KM for RAG.", s: "AGS Consulting · 2024–present" },
    hospitality: { t: "Hospitality tech-stack blueprint", b: "Created the end-to-end service blueprint for a hospitality franchise that determined the tech-stack roadmap for multi-location build-outs.", s: "AGS Consulting · 2024–present" },
    ventures: { t: "Zero → profitable exit, more than once", b: "Designed the business model, tech stack, and service models for multiple partnered ventures — growing a community product business to profitability on word of mouth alone and a vending business to profitability and exit.", s: "AGS Consulting · 2024–present" },
    agsage: { t: "Zero → five-figure months in six months", b: "Built a leadership-development practice from scratch — structured the offer and go-to-market strategy to land clients from day one, grew it to five-figure revenue months within six months, and ran it for three years.", s: "AG Sage · 2020–22" },
    selprograms: { t: "SEL & leadership curricula", b: "Designed multi-month social-emotional learning and leadership programs for high school and college students, custom curriculum retreats, and a five-figure 1:1 offer with course material, tools, and interaction cadences.", s: "AG Sage · 2020–22" },
    campsdt: { t: "67% retention lift via Self-Determination Theory", b: "Redesigned a decade-old staff-in-training curriculum at one of the country's largest residential camps (1,500 people) using SDT as the leadership framework — driving a 67% year-over-year staff retention increase, with individualized development plans across the staff.", s: "Greene Family Camp · 2014–21" },
    campops: { t: "A 1,500-person daily operation", b: "Owned end-to-end campus operations — supply ordering, programming logistics, and daily activity flow — and designed programming across roles from Head Counselor (leading 40 counselors) to Program Director.", s: "Greene Family Camp · 2014–21" },
    delta: { t: "Delta × SCADpro innovation engagement", b: "Led a cross-cultural team of creatives from eight countries and nine disciplines developing sustainable business models for thousands of obsolete beverage carts — architecting the prioritization frameworks that anchored decisions in client-adoption logic, and presenting regularly in corporate rooms.", s: "Delta Air Lines × SCADpro · 2019–20" },
    carriers: { t: "20 trucks, 100,000 sq ft, 200+ staff", b: "Ran the largest location of a university-logistics startup across six seasons. The operational playbook propagated to other campuses; reforming the systems and org structure drove a 60% resource reduction, while hiring and training 50–100 people a year.", s: "Campus Carriers · 2017–20" },
    eaas: { t: "A new B2B2C revenue line", b: "Pioneered a leadership-development curriculum across seven partner universities — a multi-stakeholder service spanning parents, students, and universities, owned end-to-end from primary market research to educational design and offer design.", s: "Campus Carriers · 2019–20" },
    film: { t: "Six to twelve productions at once, for six years", b: "Ran concurrent film productions on time, on budget, and on vision with ~95% crew retention project-to-project — including a branded film for Hamilton Watches across 30+ crew, 20+ talent, eight locations, and ten-plus vendor partners.", s: "Freelance Film & TV · 2013–19" },
    filmad: { t: "The on-set nexus", b: "As Assistant Director, visually mapped crew, cast, and equipment positioning for hundreds of scenes across 40 projects — coordinating thousands of crew, cast, equipment, locations, and vendors live on set as the nexus for information, decisions, and de-escalation.", s: "Freelance Film & TV · 2013–19" },
    filmtalent: { t: "Talent developed on set", b: "Identified underutilized talent, trained them through on-set mentor matching, and launched them to lead their own crews — building teams skilled in both leading and following so up to four production teams could dispatch in parallel.", s: "Freelance Film & TV · 2013–19" },
    bananas: { t: "The Fans First prototype", b: "First hire on the entertainment team during the alpha run — developed the prototype fan experiences the Savannah Bananas later scaled to global fame, contributing directly to a 500% social-media surge and the first ever sold-out season (250,000 fans).", s: "Savannah Bananas · 2018" },
    gallup: { t: "Gallup-certified strengths coach", b: "7+ years as a certified strengths coach, applying strengths-based development to individuals and teams.", s: "Gallup · 2019–present" },
    writing: { t: "20–50 pages a week, for a decade", b: "Ten years of sustained creative and business writing — the engine behind engaging user stories, strategic recommendations, and executive communication.", s: "Ongoing practice" },
    masters: { t: "M.A. in Service Design", b: "Savannah College of Art and Design — alongside a B.F.A. in Business for Film and Television with a Writing minor, and a Design for Urban Mobility certificate from the University of Amsterdam.", s: "SCAD · UvA" },
    translate: { t: "Trilingual: engineering, business, design", b: "Fluent in all three languages — translating business jargon to design requirements, engineering capabilities to business possibilities, and design visions to engineering roadmaps.", s: "Working style" },
  },
  categories: [
    {
      id: "people", name: "People Leadership", hue: "#f2a08a",
      skills: [
        ["Coaching", 2, ["gallup", "agsage"]],
        ["Mentoring", 2, ["filmtalent", "campsdt"]],
        ["People operations", 3, ["drylandhiring", "carriers"]],
        ["Hiring", 3, ["drylandhiring", "carriers"]],
        ["Onboarding", 2, ["carriers"]],
        ["Training", 2, ["campsdt", "carriers"]],
        ["Organizational design", 3, ["drylandorg", "franchise"]],
        ["Restructuring", 2, ["franchise", "drylandorg"]],
        ["Cultural intelligence", 2, ["delta"]],
        ["Hiring scorecard design", 2, ["drylandhiring"]],
        ["Performance feedback frameworks", 1, []],
        ["Conflict mediation", 1, []],
        ["Organizational change management", 2, ["franchise", "adoption"]],
        ["Leadership development", 3, ["agsage", "campsdt", "eaas"]],
        ["Employee retention", 2, ["eraf", "campsdt"]],
        ["Talent development", 2, ["filmtalent"]],
        ["Recruiting / talent acquisition", 2, ["drylandhiring", "carriers"]],
        ["Interviewing & candidate assessment", 2, ["drylandhiring"]],
        ["Team building / scaling", 2, ["drylandorg", "film"]],
        ["People management", 2, ["campops", "carriers"]],
        ["Influence without authority", 1, []],
        ["Emotional intelligence", 1, []],
        ["Behavioral psychology", 1, []],
        ["Strengths-based coaching", 2, ["gallup"]],
        ["Social-emotional learning (SEL)", 2, ["selprograms", "campsdt"]],
        ["Individual development plans (IDPs)", 2, ["campsdt"]],
        ["Workforce planning", 1, []],
        ["Change management", 2, ["adoption"]],
        ["Team leadership", 2, ["film", "delta"]],
      ],
    },
    {
      id: "strategy", name: "Strategy & Business Design", hue: "#f2c26b",
      skills: [
        ["Strategic visioning", 1, []],
        ["Roadmapping", 2, ["hospitality"]],
        ["Operational efficiency", 3, ["dryland450", "carriers"]],
        ["Stakeholder management", 2, ["delta", "film"]],
        ["Consulting", 2, ["franchise", "hospitality"]],
        ["Operating model design", 3, ["dryland450"]],
        ["Playbooks", 3, ["dryland450", "carriers", "adoption"]],
        ["Business model design", 2, ["delta", "ventures"]],
        ["Service strategy", 2, ["eaas"]],
        ["Product strategy", 2, ["llm", "cdp"]],
        ["Product roadmaps", 1, []],
        ["Service roadmaps", 1, []],
        ["Business roadmaps", 1, []],
        ["Value identification", 1, []],
        ["Go-to-market planning", 2, ["agsage"]],
        ["Market segmentation", 1, []],
        ["OKRs", 1, []],
        ["KEIs", 1, []],
        ["KPIs", 1, []],
        ["Strategic positioning", 1, []],
        ["Pattern recognition", 1, []],
        ["Capability mapping", 1, []],
        ["RACI", 1, []],
        ["Scenario planning", 1, []],
        ["Facilitation", 3, ["workshops"]],
        ["Vendor selection", 2, ["cdp"]],
        ["Tool & technology evaluation", 2, ["cdp", "pmsystem"]],
        ["Contract scoping", 1, []],
        ["Statement of work writing", 1, []],
        ["Pricing strategy", 2, ["agsage"]],
        ["Packaging design", 1, []],
        ["Offer design", 2, ["agsage", "eaas"]],
        ["Organizational maturity assessment", 1, []],
        ["Business development", 2, ["agsage"]],
        ["Strategic recommendations", 1, []],
        ["Business transformation", 3, ["drylandorg", "franchise"]],
        ["Digital transformation", 2, ["adoption"]],
        ["Strategic planning", 1, []],
        ["Corporate strategy", 1, []],
        ["Operational excellence", 1, []],
        ["Process improvement", 2, ["carriers"]],
        ["Process optimization", 1, []],
        ["Continuous improvement", 1, []],
        ["Business operations", 2, ["dryland450"]],
        ["Strategy & operations", 1, []],
        ["Innovation frameworks", 2, ["delta"]],
        ["Stakeholder alignment", 2, ["eraf"]],
        ["Stakeholder engagement", 1, []],
      ],
    },
    {
      id: "service", name: "Service, Experience & Systems Design", hue: "#8ecdf0",
      skills: [
        ["Service blueprinting", 3, ["blueprint20k", "dryland450", "hospitality"]],
        ["Journey mapping", 3, ["journey2250", "blueprint20k"]],
        ["Journey management", 2, ["blueprint20k"]],
        ["Experience Management (XM)", 1, []],
        ["Experience design", 3, ["bananas", "campops"]],
        ["Solution architecture", 2, ["pmsystem"]],
        ["Workshop facilitation", 3, ["workshops"]],
        ["UX architecture", 2, ["siterebuild"]],
        ["Design sprint facilitation", 1, []],
        ["User story writing", 2, ["scrumboard"]],
        ["Service mapping", 2, ["eraf"]],
        ["Persona design", 3, ["personas", "blueprint20k"]],
        ["Agentic personas", 3, ["personas"]],
        ["Continuous discovery", 1, []],
        ["Human centered design", 2, ["workshops", "udp"]],
        ["Opportunity solution tree", 1, []],
        ["Jobs to be Done framing", 1, []],
        ["Customer journey", 2, ["journey2250"]],
        ["Prototype testing", 2, ["uat"]],
        ["Gap identification", 2, ["siterebuild"]],
        ["Service design", 3, ["blueprint20k", "masters"]],
        ["Design strategy", 2, ["udp", "delta"]],
        ["Prototyping", 2, ["bananas"]],
        ["Customer experience (CX) strategy", 2, ["siterebuild"]],
      ],
    },
    {
      id: "research", name: "Research & Discovery", hue: "#b5dd8a",
      skills: [
        ["User research", 2, ["siterebuild", "cdp"]],
        ["Stakeholder interviews", 2, ["franchise"]],
        ["Contextual inquiry", 1, []],
        ["Synthesizing research", 2, ["siterebuild"]],
        ["Actionable insights", 1, []],
        ["Ethnographic field research", 3, ["eraf", "franchise"]],
        ["Product discovery", 2, ["siterebuild"]],
        ["User interviews", 2, ["franchise"]],
        ["Interview design", 1, []],
        ["Research design", 2, ["cdp"]],
        ["Testing design", 2, ["uat", "drylandhiring"]],
        ["AI for research", 2, ["personas"]],
      ],
    },
    {
      id: "ai", name: "AI & Emerging Technology", hue: "#c7a6f2",
      skills: [
        ["Generative AI strategy", 3, ["adoption", "llm"]],
        ["AI-augmented strategic document production", 2, ["km"]],
        ["AI-augmented design thinking workflows", 2, ["personas"]],
        ["Synthetic users", 3, ["personas"]],
        ["Virtual personas", 2, ["personas"]],
        ["AI implementation strategy", 2, ["adoption"]],
        ["Prompt engineering", 3, ["prompttemplate"]],
        ["Custom GPTs", 2, ["teamsagent"]],
        ["Custom GPT development & deployment", 2, ["teamsagent"]],
        ["AI-augmented operating workflows", 2, ["km"]],
        ["AI evangelism", 2, ["adoption"]],
        ["Stakeholder education", 2, ["adoption"]],
        ["LLM workflow orchestration", 2, ["km"]],
        ["Agentic design", 3, ["personas", "km"]],
        ["Agent design", 2, ["teamsagent"]],
        ["Retrieval augmented generation literacy", 2, ["km"]],
        ["Prompt design", 1, []],
        ["Digital change management", 2, ["adoption"]],
        ["AI adoption", 3, ["adoption"]],
        ["AI ethics", 1, []],
        ["Responsible AI", 1, []],
        ["AI transformation", 2, ["franchise", "km"]],
        ["AI enablement", 3, ["adoption", "prompttemplate"]],
        ["AI upskilling & training", 2, ["adoption"]],
        ["Adoption measurement", 2, ["adoption"]],
        ["Adoption metrics", 1, []],
      ],
    },
    {
      id: "ops", name: "Operations & Delivery", hue: "#7fdec2",
      skills: [
        ["System architecture", 2, ["pmsystem", "dryland450"]],
        ["Knowledge management architecture", 3, ["km"]],
        ["Resource management", 2, ["carriers", "filmad"]],
        ["Cross-functional collaboration", 2, ["campops"]],
        ["Cross-functional facilitation", 2, ["journey2250"]],
        ["Cross-cultural facilitation", 2, ["delta"]],
        ["Customer Data Platforms", 2, ["cdp"]],
        ["Program management", 2, ["journey2250"]],
        ["Project management", 3, ["film", "delta"]],
        ["Cross-functional leadership", 2, ["delta"]],
        ["Implementation planning", 2, ["filmad"]],
        ["Workflow automation", 2, ["pmsystem"]],
      ],
    },
    {
      id: "comms", name: "Communication & Writing", hue: "#f2aed0",
      skills: [
        ["Strategic documentation", 2, ["dryland450", "adoption"]],
        ["Storytelling for business audiences", 2, ["delta"]],
        ["Executive communications", 2, ["dryland450"]],
        ["Advising", 1, []],
        ["Translating between engineering / design / business", 2, ["translate"]],
        ["Instructional design", 2, ["campsdt", "selprograms"]],
        ["Learning experience design", 2, ["eaas"]],
        ["Curriculum design", 3, ["selprograms", "campsdt", "eaas"]],
        ["Workshop design", 2, ["workshops"]],
        ["Pitching", 2, ["delta"]],
        ["Presenting", 2, ["workshops"]],
        ["UX writing", 1, []],
        ["Strategic narrative writing", 2, ["writing"]],
        ["Long form essay writing", 2, ["writing"]],
        ["Public speaking", 2, ["workshops"]],
        ["Workshop hosting", 1, []],
      ],
    },
    {
      id: "methods", name: "Methodologies & Frameworks", hue: "#a7b6f2",
      skills: [
        ["Agile methodology", 2, ["scrumboard"]],
        ["Lean methodology", 1, []],
        ["Sprint planning", 1, []],
        ["Story refinement", 2, ["siterebuild"]],
        ["Backlog refinement", 2, ["siterebuild"]],
        ["UAT (User Acceptance Testing)", 3, ["uat", "personas"]],
        ["A/B testing", 1, []],
        ["Usability testing", 2, ["uat"]],
        ["Design thinking", 3, ["workshops"]],
        ["Systems thinking", 3, ["eraf", "blueprint20k"]],
        ["Lateral thinking", 1, []],
        ["Abductive reasoning", 1, []],
        ["Root cause thinking", 2, ["eraf"]],
        ["Structured problem solving", 2, ["delta"]],
      ],
    },
    {
      id: "tech", name: "Tools & Technology", hue: "#c9d2dc",
      skills: [
        ["Miro", 3, ["workshops", "blueprint20k"]],
        ["TheyDo", 2, ["blueprint20k"]],
        ["Notion", 1, []],
        ["Motion", 1, []],
        ["Claude Code", 2, ["km"]],
        ["Claude Cowork", 2, ["km"]],
        ["Claude API", 1, []],
        ["Agentic AI tools", 2, ["km", "teamsagent"]],
        ["ChatGPT / OpenAI API", 1, []],
        ["Obsidian", 2, ["km"]],
        ["Mural", 1, []],
        ["Monday", 2, ["pmsystem"]],
        ["Slack", 1, []],
        ["Zoom", 1, []],
        ["Microsoft 365", 1, []],
        ["Google Suite", 1, []],
        ["Dropbox", 1, []],
        ["Aha!", 1, []],
        ["Loom", 1, []],
        ["Asana", 1, []],
        ["ClickUp", 2, ["pmsystem"]],
        ["Jira", 1, []],
        ["Profit.co", 1, []],
        ["Shopify", 1, []],
        ["MAXQDA", 1, []],
        ["DisplayR", 1, []],
        ["QuestionPro", 1, []],
      ],
    },
  ],
};
