/* ============================================================
   SKILLS CONSTELLATION — ALL CONTENT LIVES HERE.
   Edit this file to change anything on the map; no code changes needed.

   categories[].skills: [ "Name", weight, [evidenceIds] ]
     weight 3 = signature strength (large star, opens proof)
     weight 2 = proven in practice (medium star, opens proof)
     weight 1 = working skill (small star, part of the field)
   evidence: id -> { t: title, b: body, s: years-of-experience line }
   Evidence is transcribed verbatim from "Fit Map Details.md"
   (finalized 2026-07-31) — never edit card text here; edit the bank
   and re-sync.
   ============================================================ */
window.MAP_DATA = {
  person: {
    name: "Ryan Hance",
    title: "A Complete Map of Practice",
    sub: "Every skill in the set — untailored, unabridged. Bright stars carry the story behind them.",
  },
  evidence: {
    /* -- Experience & Credentials -- */
    sd7: { t: "7+ Years of Service Design", b: "7+ years as a practicing service designer with an advanced degree in the specialty, but 13+ years designing how people move through complex products, services, and operations — including service design, innovation, and design strategy roles across multiple startups and Fortune 500 corporations; Delta Air Lines and Bayer.", s: "" },
    client13: { t: "13 Years of Client-Facing Delivery", b: "My career began with 6 years leading client work in film and TV + advertising and music videos. Since then, 7 years of client implementation, consulting, and stakeholder management across startups, nationwide franchises, Delta Air Lines, and Bayer.", s: "" },
    ma: { t: "Business Innovation M.A.", b: "M.A. in Business Innovation from SCAD's De Sole School of Business Innovation — essentially an MBA crossbred with service design, built for intrapreneurship and using design thinking to influence decision making. My B.F.A. is from SCAD as well; business for film and television.", s: "" },
    credentials: { t: "Additional Credentials & Training", b: "Beyond my Business Innovation M.A. and my B.F.A. in entertainment business from SCAD, I am a Gallup Certified Strengths Coach. Additionally, I have a certificate in Design for Urban Mobility from the University of Amsterdam, and have done multiple innovative business trainings in niche and offer design via Traffic & Funnels and offers, leads, and business models via Acquisition.com and their events.", s: "" },
    industries: { t: "Wide Industry Experience", b: "Experience across 10+ industries and hundreds of niche personas across unrelated service verticals — film and TV, agriculture, counseling, fitness, hospitality, education, logistics, sports entertainment. I learn fast, dive deep, and have a proven ability to onboard quickly to and lead in any business domain.", s: "14+ years experience" },
    /* -- Service, Experience & Systems Design -- */
    blueprinting: { t: "Service Blueprinting", b: "Built service blueprints at every scale from a 450-point blueprint for a startup's information architecture and executive decision making to a 20,000+ point global, enterprise level blueprint to identify service, product, technology, and operational gaps and opportunities at Bayer.", s: "7+ years experience" },
    presentfuture: { t: "Present State vs Future State", b: "I map the present state of an organization, business unit, or stakeholder journey to design the future state. The global blueprinting effort at Bayer existed to identify the present state of our tech stack and operational interactions and then make recommendations for future state: we delivered a present state map and a future state map. I did the same at Dryland Revival, mapping our current processes and then identifying new product and service opportunities for our customers and better ways of working for our teams.", s: "10+ years experience" },
    journeymapping: { t: "Journey Mapping", b: "I have mapped journeys across startups, national franchises, and the Fortune 500. At Bayer I facilitated a global journey mapping effort spanning North America, Europe, and Asia-Pacific, 2,250 journey points across 27 teams, that cut environmental toxin risk 70% and raised workplace safety 30% within two quarters. At Dryland, the customer and employee journeys inside our 450 point blueprint became the source for our playbooks, org design, and project management system. I led the migration of Bayer's global, enterprise level blueprint from Miro to TheyDo so the journeys could be managed more accurately and dynamically.", s: "7+ years experience" },
    journeymgmt: { t: "Journey Management", b: "At Bayer I managed the primary customer journey inside our customer platform's 20,000+ point global blueprint, and led a separate 2,250 point journey mapping effort across 27 teams, mapping the employee journeys of our operations platform. I additionally led the migration of the entire customer platforms blueprint from Miro to TheyDo, creating customer journey management and enablement at the enterprise level, so the organization could keep making decisions from it as the operation changed. At Dryland, the journeys inside our 450 point blueprint were the source for our playbook library, our org design, and the project management system.", s: "7+ years experience" },
    regulatory: { t: "Regulatory & Compliance", b: "Regulatory and compliance ownership started on film sets as an Assistant Director, where I was in charge of safety and compliance on set, responsible for cast, crew, and vendors across 40 productions. At the enterprise level, I built a layered journey map across 27 teams on Bayer's operations platform for a confidential regulatory compliance effort. I currently work with highly regulated industries like counseling.", s: "10+ years experience" },
    systemsmapping: { t: "Systems Mapping", b: "I build maps that help teams see the bigger picture and communicate and make decisions more efficiently. At Dryland Revival, I built a map with 100+ interaction points across all five departments. I have built comparative org charts that let a nationwide franchise see its restructure clearly enough to reorganize without a single layoff, current and future state organizational maps for entire Fortune 500 divisions, and the visual maps of crew, cast, and equipment that ran thousands of production days across six years in the film industry.", s: "13+ years experience" },
    ia: { t: "Information Architecture", b: "I structure information so people, teams, and technology can equally increase efficiency with it. I have been designing the automations and information architecture of project management systems since working in the film industry, and recently developed enterprise-wide IA for PM systems at Dryland Revival. At Bayer, I designed the information architecture of the agentic persona service, and mapped the data source architecture of the global, enterprise level future state service blueprint and tech stack recommendations. Today I architect AI native, tool agnostic knowledge systems with project flow automations and documentation structures for both human and agent ease of retrieval paired.", s: "10+ years experience" },
    systemsthinking: { t: "Systems Thinking", b: "I live in a constant state of mapping systems in my head. It is what allowed me to excel at the rapid, leadership-level decision making of being an Assistant Director on set in the film industry and helps me see consequences of business decisions that most others don't. When I walk into a room, a team, or a company, I have the system mapped in my head immediately. The blueprints, frameworks, and playbooks I design are made to help others act with the level of empathy their stakeholders need.", s: "13+ years experience" },
    rootcause: { t: "Root Cause Solutioning", b: "I'll spend an entire day on a single problem, because I know that resolving the system instead of the symptom saves days, weeks, or months of work later. And not just for me, but for entire teams, divisions, or organizations as a whole.", s: "13+ years experience" },
    prototyping: { t: "Prototyping", b: "Build context appropriate prototypes, low to high fidelity, to make ideas testable and accessible to feedback and usability. Some examples: agentic user personas built and validated inside a Fortune 500 before commercial AI tools existed, sustainable business model prototypes for Delta, and the Fans First experiences the Savannah Bananas scaled to global fame. Not to mention the rapid prototyping of sites, tools, maps, and apps in the AI era.", s: "13+ years experience" },
    xd: { t: "Experience Design", b: "I have been designing experiences professionally for over a decade. At the end of six years in the entertainment industry, I helped develop and execute the prototype \"Fans First\" experience that became the standard the Savannah Bananas then scaled to global fame. Before that, I employed experience design principles to innovate on decades old traditions as Program Director of a 1,500 person summer camp, and taught those principles to the next generation of camp leaders. Since then, I designed multi-stakeholder experiences at Delta Air Lines and Campus Carriers, lead the end-to-end farmer experience at Bayer across marketing, product, and portal surfaces, and employee and customer experiences at Bayer, Dryland Revival, and the national franchises I work with at AGS.", s: "13+ years experience" },
    productlead: { t: "End-to-End Product Leadership", b: "UX Lead on Bayer's end-to-end customer site rebuild, acting as the design side Product Manager — from the public marketing pages through the post log in customer portal — driving a 35% increase in product and service opportunities and leading user acceptance testing across the North American user base.", s: "7+ years experience" },
    techstack: { t: "Tech Stack Blueprinting", b: "Bayer's global enterprise blueprinting effort was tech stack blueprinting at the largest possible scale: mapping the present state of every tech stack, persona, and operational interaction across multiple countries, then delivering future state recommendations that exposed redundant systems and unserved gaps. At Dryland, the 450 point blueprint drove the design and redesign of our entire tech stack, from the original ClickUp buildout to a Monday.com rebuild and the Zapier automations connecting it all. I still do this for clients today, including the end-to-end service blueprint and strategic recommendations that determined a hospitality franchise's tech stack roadmap for multi-location build outs.", s: "7+ years experience" },
    designstandards: { t: "Design Standards", b: "Authored Bayer's Universal Design Principles, adopted across every platform under the Head of Design for the $27B Crop Sciences division.", s: "4+ years experience" },
    architectoperator: { t: "Architect and Operator", b: "Because my background is in operations and my expertise is in designing, I develop strategic roadmaps that don't die in the purgatory between planning and executing. Before becoming a designer by training, I ran ops for a 1,500-person summer camp, a university logistics startup — a 20-truck fleet, a 100,000-square-foot warehouse, 200+ seasonal staff, and hundreds of projects in the entertainment industry.", s: "13+ years experience" },
    designfluency: { t: "Design Fluency", b: "I'm a trained service designer with a background in operations and leading teams. My fluency in design work allows me to ask the right questions and spot risk early, because I've built the blueprints, run the research, and facilitated the workshops myself.", s: "7+ years experience" },
    /* -- Research & Discovery -- */
    research: { t: "Research & Discovery", b: "Discovery is where I start every engagement and conversation. Masters level training + 7 years of real world experience in ethnographic field research, stakeholder interviews, contextual inquiry, and journey mapping to turn workforce challenges into actionable solutions.", s: "7+ years experience" },
    prioritization: { t: "Prioritization via Insights", b: "As a strategist, I prioritize actions and roadmaps via active analysis. This is a muscle that has been being trained since running film sets and having to make significant, long term decisions live in the moment. I was then given the tools and additional frameworks in grad school where my research and prioritization skillsets were trained intentionally. At Bayer, ethnographic user discovery overturned product decisions external consultancies had built from business stakeholder input alone. At Delta, passing our concepts through a business model canvas reset the entire direction of the engagement. At Dryland, interviews with team leads redirected employee retention efforts, and now I guide executive teams in efforts that affect their entire company.", s: "13+ years experience" },
    researchtools: { t: "Research & Analytics Tools", b: "Masters level training + 7 years of real world experience in research and analysis as well as their most premium tools: MAXQDA for qualitative coding, DisplayR and QuestionPro for survey and quantitative analysis, plus the discovery toolkit of interviews, contextual inquiry, and ethnographic field research behind them.", s: "7+ years experience" },
    testing: { t: "Testing & Validation", b: "Led User Acceptance Testing across a Fortune 500's North American user base, built agentic personas validated above 80% by 20+ year subject matter experts that cut UAT failures, and always run usability and prototype testing to pressure test ideas before they ship.", s: "7+ years experience" },
    vendorselection: { t: "Vendor Selection", b: "Drove the research and strategy that anchored Bayer's selection of its enterprise Customer Data Platform vendor, then structured the governance team that integrated it, translating between what the business needed, what the technology could do, and what the users would actually adopt. I have been selecting technologies and vendor partners since my film days, that could look like researching, building relationships with, and engaging 10+ external vendor partnerships on a single branded film. At Dryland, I selected our project management platform, built it end to end in ClickUp, then deliberately re-selected and rebuilt in Monday.com because the mobile experience served our field crews better. I regularly self train on unfamiliar enterprise software to the depth of evaluating vendor fit, and I evaluate against the workflows and journeys of all of the stakeholders, who will interact with tool from different directions.", s: "13+ years experience" },
    orgrestructuring: { t: "Organizational Restructuring", b: "I have restructured organizations in three settings. A nationwide counseling franchise across multiple states: ethnographic interviews with corporate and franchisees, comparative org charts, and a Franchise Criteria Canvas that gave corporate a clear standard, with locations closed, folded, and opened and headquarters reorganized without a single layoff. Dryland Revival: an org redesign that detached the CEO from daily hands on work, doubling revenue and quadrupling headcount in three months. Campus Carriers: reformed the organizational structure and operational systems of the university logistics operation for a 60% resource reduction.", s: "9+ years experience" },
    metricsdesign: { t: "Metrics Design", b: "Masters level training in metric determination: designing the right success metrics for the situation, then measuring against them. Fluent in OKRs, KPIs, NPS, adoption rate, time to launch, and satisfaction. Decision criteria that anchored client adoption logic in my work with Delta, the Franchise Criteria Canvas and priority matrices that gave a nationwide franchise an agreed standard for franchisee decisions, the SME validation threshold that gated Bayer's agentic personas before teams were allowed to rely on them, and the performance analytics, trackers, and dashboards Dryland ran on. Regularly measuring outcomes against the vision that was set: a 35% lift in product and service opportunities, a 30% rise in workplace safety, and 2% to 26% platform adoption in two months.", s: "7+ years experience" },
    /* -- Strategy & Business Design -- */
    gtm: { t: "Go-to-Market & Offer Design", b: "Structured the offer and go-to-market strategy for seven intrapreneurial and entrepreneurial ventures: an internal agentic tool at Bayer, sustainable products at Delta Air Lines, an education as a service line with Campus Carriers, the business model for Dryland Revival, multiple successful leadership practices, my franchise consulting business. Formal training in business modeling and GTM strategy (M.A. program at SCAD), niche and offer design (Traffic & Funnels) and offers, leads, and business models (Acquisition.com). I take an opportunity from value proposition to packaging, and into a working product or service.", s: "7+ years experience" },
    bizmodel: { t: "Business Model Design", b: "Designed business models, tech stacks, and service models across many engagements: agentic tools within Bayer, sustainable business models for Delta's obsolete beverage carts, a construction-science startup's operating model, a B2B2C education as a service for Campus Carriers, a hospitality franchise's multi-location tech roadmap, and five personal ventures grown to profitability.", s: "7+ years experience" },
    pmroadmap: { t: "Product Management & Roadmapping", b: "Being a producer in the film industry was a 1:1 mirror of product management: understand the client's vision, close the gap between what they think is possible and what the timeline and budget allow, build the roadmap, own delivery, develop and lead teams. Running six concurrent productions on average mirrors running parallel product lines, each with its own stakeholders, budget, and hard ship date. After a masters degree that specifically focused on the intersection of business and design, I carried that operating model into Fortune 500 environments, leading product and project management for a sixteen person, eight country, nine discipline team developing sustainable business models for Delta Air Lines. Then at Bayer: acting as the design-side Product Manager for the end-to-end farmer experience, leading strategic input and user testing on Bayer's internal LLM platform build, determining the platform-wide integration roadmap of the Customer Data Platform, the internal AI product roadmap, plus backlog refinement, user story writing, and building out an agile scrum board for a legacy platform team that had none.", s: "13+ years experience" },
    decisionframeworks: { t: "Decision Frameworks", b: "I am a strategic framework and decision model library, and I use these tools to help teams uncover information, connect dots, and communicate clearly. If I don't have a tool perfect for helping a team make a decision, I design one in the moment. I've been building these tools myself and using them with teams professionally since working in the film industry, so I have a backlog of hundreds of models and frameworks going back 10+ years, not to mention the hundreds that I have collected from other great thought leaders.", s: "13+ years experience" },
    advising: { t: "Strategic Advising", b: "My strategic advising goes back to film and TV, where the producer's first job is advising the client on their own vision: what is actually possible within the timeline and budget, and what it will take to get there. Since then: primary client contact for Delta Air Lines leading a sustainability marketing effort, almost eight years of coaching leaders through my own practices, and advising for franchisees and franchisors today.", s: "13+ years experience" },
    processopt: { t: "Process Optimization", b: "My background in film means that the first half of my career required doing literally unbelievable things with scarce resources. Now, I reengineer systems to allow for the streamlining of resources that will exercise the greatest efficiency. I helped a university logistics operation restructure for a 60% resource reduction, built a startup playbook library that lifted efficiency 80% and removed the CEO from lower-level decisions, and developed operating cadences and management systems that kept teams aligned through rapid growth in both my entertainment industry days and my startup experiences.", s: "13+ years experience" },
    mission: { t: "Mission Driven Work", b: "Mission driven work runs through my whole career, not just my corporate credits. Seven summers on staff at a camp serving thousands of kids each year. Almost eight years of leadership development: multi-month social emotional learning and leadership programs for high school and college students, and the cohort based men's work, retreats, and gatherings I still run for men today. I turned thousands of Delta's obsolete beverage carts into sustainable opportunities aligned to the airline's brand and environmental goals, and led journey mapping work at Bayer that cut environmental toxin risk 70% and raised workplace safety 30% within two quarters. Plus the Presidential Service Award for volunteering in my community and multiple excursions volunteering to lead groups through war torn countries.", s: "12+ years experience" },
    /* -- Startup & Transformation -- */
    startupos: { t: "Startup Operating Systems", b: "I have built the operating systems of two startups. At Campus Carriers, a university logistics startup, I ran the largest location — a 20 truck fleet, a 100,000 square foot warehouse, and 200+ seasonal staff. I built the operational playbook covering recruiting, onboarding, training, scheduling, inventory, and safety that drove a 60% resource reduction and propagated across the other partner campuses, while pioneering an education as a service revenue line on top of it. At Dryland Revival, as co-founder and second hire, I built the operating system as we grew from one client to a profitable exit: playbooks, hiring funnel, project management system and tech stack, and the org redesign that let the CEO focus on his highest leverage work.", s: "9+ years experience" },
    changemgmt: { t: "Change Management", b: "Drove change and adoption in resistant systems my entire career: from navigating day-to-day and hour-by-hour changes on film sets to innovating decades old traditions while keeping the soul of the experience at a 1,500 person summer camp, including a decade old training program replaced with modern methods, creating a 67% year over year retention lift; a nationwide counseling franchise led through restructuring across states without a single layoff; a startup org redesign that doubled revenue and quadrupled headcount; moving a construction field crew into modern technology in the context of a phone based project management system; and leading a Fortune 500 AI platform from 2% to 26% adoption in two months.", s: "12+ years experience" },
    cadences: { t: "Operating Cadences", b: "Ran daily risk tracking and hour by hour plans across teams of 15 to 60 and multiple concurrent productions in the film industry. At Bayer, I built the scrum board, wrote the stories, and led scrum for a legacy platform team that had no ceremonies at all. At Dryland, I owned the operating cadences and reporting: the all hands meetings, trackers, and dashboards that all six teams ran on through a growth window that doubled revenue and quadrupled headcount year over year. Actively leading interaction cadences throughout my coaching programs the last eight years. Led operating cadences at Campus Carriers, Greene Family Camp, and the Delta Air Lines effort as well.", s: "13+ years experience" },
    revenue: { t: "New Revenue Lines", b: "I have pioneered new revenue lines across startups, franchises, and the Fortune 500. Developed a B2B2C education as a service line at Campus Carriers, owned end to end from primary market research through curriculum design, offer design, and pre-launch partnerships across seven partner universities. New service offerings designed and launched at Dryland Revival through a growth run that doubled revenue year over year for three years. Sustainable business models for thousands of Delta's obsolete beverage carts. An operations and marketing transformation at a physical health franchisee that opened the path to a second location. And my own ventures: a bicycle rental marketplace for a university, a community based product business grown to profitability, a vending machine business grown to profitability and exited, and multiple coaching and consulting practices grown to recurring five figure months.", s: "13+ years experience" },
    entrepreneurial: { t: "Entrepreneurial Mindset", b: "Grew multiple ventures from zero to profitable exit — a bicycle rental venture in college, a construction sciences startup in Washington, a community based product business and vending machine business in Atlanta, and multiple consulting and coaching practices working with teens and young professionals to franchises and community and business leaders.", s: "12+ years experience" },
    bizdev: { t: "Business Development", b: "Built three consulting and coaching practices from scratch — structuring the offer, pricing, and go-to-market to land clients from day one, and led the business development that kept each running for 3+ years with consistent five-figure engagements. Led project development in the film industry before that, and led an effort selling an agentic persona service intrapreneurally at Bayer.", s: "10+ years experience" },
    workforce: { t: "Workforce Transformation", b: "Workforce transformation in four settings: Bayer's employee experience platform, end to end people operations at Dryland Revival from hiring funnel to playbooks, the nationwide restructuring of a counseling franchise, and multiple entertainment industry efforts restructuring teams after budget and timeline changes.", s: "10+ years experience" },
    /* -- Delivery & Operations -- */
    concurrent: { t: "Concurrent Project Management", b: "Owned film and TV productions end to end as the client's point of contact, delivering on time and on budget while running an average of six concurrent productions, peaking at ten to twelve multiple times. Currently managing multiple engagements with AGS.", s: "10+ years experience" },
    highstakesenv: { t: "High Stakes Environments", b: "As a producer and assistant director in the entertainment industry, plans had to be precise, teams had to be well-qualified, and the roadmap had to be intentional. If we had to push a day, we might be literally wasting a million dollars, and that responsibility fell directly on me. This was normal as a work environment for me for six years.", s: "13+ years experience" },
    highstakesdecisions: { t: "High Stakes Decision Making", b: "As an assistant director and production coordinator in the entertainment industry, my brain was the on-set hub for information, prioritization, and decision-making across 40 productions, coordinating thousands of crew, cast, and vendors live — and de-escalating the \"whatever can go wrong will go wrong\" situations.", s: "13+ years experience" },
    constraints: { t: "Working Within Constraints", b: "As a producer and assistant director, my whole job was making the client and directors' visions possible despite budget, time, and resource constraints — I developed the concept and vision, roadmapped, and implemented the operational plan across years of productions. This has translated directly to my skillsets in producing quality work creatively since.", s: "13+ years experience" },
    clientdelivery: { t: "End-to-End Client Delivery", b: "Six years in film and TV owning productions end to end as the client's point of contact, on time and on budget across roughly 50 productions, including a branded film for Hamilton Watches spanning 30+ crew, 20+ talent, eight locations, and ten-plus vendor partners. Then Delta, where I was the primary contact between client and team, presenting at corporate while translating business needs to the creative team in the studio. Today I own consulting engagements end to end for franchisors, franchisees, and service businesses, from scoping and discovery through implementation and adoption.", s: "13+ years experience" },
    financials: { t: "Financials Ownership", b: "Owned client communication, budgets, timelines, and resource management in film and TV for years, where a blown day meant hundreds of thousands to millions of dollars. Additionally have Masters level training in financial modeling. P&Ls, forecasting, income statements, balance sheets, cash flow modeling, scenario modeling, valuation modeling, pricing modeling, startup runway modeling, revenue modeling, and budgeting.", s: "13+ years experience" },
    engagement: { t: "Engagement Ownership", b: "I lead multiple concurrent client engagements end to end, owning scoping, timeline, and delivery from discovery through handoff. This skillset developed in film and TV first, where our crew averaged six productions at a time and peaked between ten and twelve. I also owned multiple engagements with business stakeholders as a design leader at Bayer and Delta Airlines.", s: "13+ years experience" },
    inherited: { t: "Evaluating Inherited Work", b: "I am regularly handed someone else's work and asked to move forward from where they left off. This was common in the film industry and most of my efforts in other operational capacities like at Campus Carriers and Greene Family Camp. At Bayer, my first assignment on the operations platform was user acceptance testing with zero context on products built before we arrived. Additionally, my first assignment with the customer platform was to take over ownership of the primary user experience for the end-to-end farmer site rebuild, where I immediately discovered a gap in designing for user trust by the external consultancies. Entering a project without the builders' context is an advantage, because most users of a product, service, or system do not have that context either.", s: "10+ years experience" },
    resourcereduction: { t: "Resource Reduction", b: "Leading film industry efforts required creative prioritization to arrive at the final vision on time and on budget. Another example is the reformation of the operational systems and org structure at a university logistics startup — a 100,000 square foot warehouse, a 20-truck fleet, and 200+ seasonal staff — where I then documented the new ways of working into the playbook that propagated across all campuses. The reform drove a 60% resource reduction. This was all pre-service design and business modeling expertise, the framework I have used to make and communicate these decisions across my Fortune 500 and consulting work since.", s: "10+ years experience" },
    liveevents: { t: "Live Event Operations", b: "A decade producing live audience experiences — a full season of 100% sold out Savannah Bananas games, six years of music festival operations, and years of weekly events for a 1,500 person summer camp. Currently producing community gatherings.", s: "14+ years experience" },
    riskflagging: { t: "Early Risk Flagging", b: "Skilled at identifying delivery risk early in unfamiliar domains — a habit built through six years of film sets where the surprises required quick production-wide changes, seven years in summer camping where one lightning strike could change the plans for 500 kids for a whole day, and running operations across multiple startups.", s: "13+ years experience" },
    domainlearning: { t: "Rapid Domain Learning", b: "Joined into a Fortune 500 knowing nothing about agriculture and was shipping across four platforms within a year. Joined Dryland knowing nothing about construction sciences and grew the business to profitability within two years. Have done relevant and successful consulting work in 10+ unfamiliar domains.", s: "13+ years experience" },
    workstreams: { t: "Multiple Workstreams", b: "Like my time in the entertainment industry, summer camping, and consulting, my role at Bayer was constantly in flux. I started as the UX lead for the farmer experience, became a design strategist for the operations platforms, then lead strategist for the generative AI effort, turning a six month contract into 18 months by continuing to be useful. I ramp quickly on new problems.", s: "13+ years experience" },
    parallel: { t: "Parallel Workloads", b: "Built a startup to a profitable exit while working Bayer full time — Bayer was my 9-to-5, the startup was my 5-to-9. Two demanding roles, years of switching between them without dropping the ball. Before this, 6+ years running multiple projects at a time in the entertainment and summer camping industries in parallel. My capacity for effort is high.", s: "13+ years experience" },
    agile: { t: "Agile Experience", b: "Worked inside agile product teams across four Bayer platforms: refined backlogs, aligned hundreds of technical stories to user needs, led user acceptance testing across the North American user base, then built out the scrum board — writing all the stories and leading scrum — for a legacy platform team.", s: "4+ years experience" },
    /* -- People & Leadership -- */
    mentorship: { t: "Mentorship Experience", b: "Ran training and development for a 250 person camp staff, redesigning a program that lifted retention 67% year over year, am Gallup certified, trained leadership coach with almost eight years running my own coaching practice, and spent six years in film identifying underutilized talent, developing them through on set mentor matching, and enabling them to lead their own crews.", s: "12+ years experience" },
    trainingdesign: { t: "Training Program Design", b: "Redesigned a decade old staff training program at one of the country's largest residential summer camps (1,500 people a summer) using Self-Determination Theory as the leadership framework — driving a 67% year-over-year staff retention increase. This was after developing leadership training for the internal and external stakeholders at Campus Carriers and developing leadership programming for teens and young professionals, and before my more recent efforts designing leadership training for men 20s to 40s.", s: "7+ years experience" },
    talentdev: { t: "Talent Development", b: "Built individualized development plans across a 250 person camp staff, created a system for on set mentor matching in film that identified underused talent and launched them to lead their own crews, and design and facilitate leadership programming for the last eight years.", s: "10+ years experience" },
    retention: { t: "Team Retention", b: "I build teams that stick around. Some stats: roughly 95% crew retention across six years in film, a 67% year-over-year retention lift at a 250 staff summer camp, and a startup hiring funnel that delivered 100% season-long retention of the individuals who moved through it.", s: "10+ years experience" },
    hiring: { t: "Hiring Experience", b: "I have built and run hiring systems in three industries. In film and TV, I built and led a multi-departmental production crew with roughly 95% project to project retention across six years, identifying underutilized talent and developing them into leads through on set mentor matching. At Campus Carriers, I facilitated the seasonal staffing funnel, hiring and training 50 to 100 employees a year. At Dryland, I built the hiring funnel across three candidate markets that scaled the team from 3 to 15 in a single season and 30 to 40 hires across seasons, conducting hundreds of first round interviews and designing a paid multi-day field test that drove 100% season long retention of everyone who completed it.", s: "13+ years experience" },
    coaching: { t: "Coaching", b: "Gallup Certified Strengths Coach trained in behavior and relationship psychology; almost eight years of facilitating leadership development in the context of empathy strategies and emotional intelligence professionally. Built a leadership development practice from scratch to five figure revenue months within six months, running and iterating workshops and facilitation opportunities since. I've coached hundreds of high school and college students through multi-month social-emotional learning and leadership programs, and hundreds of others through weekend retreats, cohorts, and high ticket 1:1 men's work, with custom tools for mental and emotional processing developed in line with my systems and design thinking background.", s: "7+ years experience" },
    psychology: { t: "Human Behavior & Psychology", b: "Gallup Certified Strengths Coach trained in behavior and relationship psychology. This guides my deep empathy for user behavior, and my ability to influence change without authority. Eight years of teaching emotional intelligence and social emotional learning professionally means I can read motivations, needs and expectations, and emotions as a professional expertise, not a personality trait. I use that background to shape desirability and adoption.", s: "12+ years experience" },
    servantleadership: { t: "Servant Leadership", b: "Seven summers on staff at a summer camp serving thousands of kids, leadership development practice for high school and college students, and currently, cohort based men's work. Plus the Presidential Service Award for volunteering in my community and multiple times volunteering to lead groups through war torn countries.", s: "14+ years experience" },
    /* -- Communication & Facilitation -- */
    crossfunctional: { t: "Cross-Functional Leadership", b: "I have led across functions and disciplines my entire career. On film sets, every department head came to me as the hub for information, prioritization, and decision making across thousands of crew, cast, and vendors. At Delta, I led a cross-cultural team spanning eight countries and nine disciplines while owning budget, timelines, and the client relationship, presenting at corporate and translating business needs to the creative team in the studio. At Bayer, I aligned 27 teams that did not report to me across North America, Europe, and Asia-Pacific. At Dryland, all six teams ran on the operating systems I developed.", s: "13+ years experience" },
    crossdiscipline: { t: "Cross Discipline Fluency", b: "Fluent in business, design, and engineering languages. I love translating business jargon to design requirements, engineering capabilities to business possibilities, and design visions to engineering roadmaps. This is the product and service version of what I did as a producer and assistant director in the entertainment industry in the first half of my career.", s: "13+ years experience" },
    facilitation: { t: "Workshop Facilitation", b: "I have practiced facilitation professionally for over a decade. Hundreds of design thinking workshops from 5 to 150 people at Bayer, where Miro selected me as the sole Enterprise Advocate for a company of ~100,000 people. Staff trainings, development programming, and multi-day events for a 250 person staff at one of the country's largest summer camps. Eight years of leadership retreats, cohorts, and group trainings through my own practices, from high school and college students to the men's work I facilitate today. And the working sessions I currently run with franchise corporate teams and franchisees.", s: "12+ years experience" },
    speaking: { t: "Public Speaking & Presentations", b: "Over a decade of live presentations, from pitch decks in Fortune 500 corporate rooms to multi-day retreats, scaled coaching programs, and live events for a 1,500-person camp. Comfortable commanding a room of five people to five thousand.", s: "10+ years experience" },
    execalign: { t: "Executive Alignment", b: "At Bayer, I developed an agentic AI experience and sold it internally through months of workshops, demos, and one on one influencing before getting the greenlight to build. At Delta, I was the primary client contact, presenting status updates and pitch decks regularly to corporate. As a franchise consultant, I work directly with CEOs, executive teams, and franchisors. At Dryland, I was the CEO's first conversation and advisor on every major decision. The first half of my career in film was aligning clients and directors on what was actually possible within the timeline and budget.", s: "10+ years experience" },
    storytelling: { t: "Storytelling & Executive Narrative", b: "Ten years writing 20 to 50 pages a week of creative and business content, from user stories to executive strategy. As Delta's primary client contact I presented status updates and pitch decks in corporate rooms while translating business needs to the creative team, and I sold an agentic AI build to Bayer executives through months of workshops, demos, and one-on-one narrative.", s: "10+ years experience" },
    strategicwriting: { t: "Strategic Writing & Documentation", b: "Built upon a practice of writing 20 to 50 pages a week, I have delivered hundreds of scripts and character driven narratives, as well as hundreds of pages of strategic documentation, philosophical essays, user stories, and executive strategy. I authored Bayer's Universal Design Principles, adopted across every platform in the division, the Customer Data Platform strategy documentation that anchored vendor selection at the enterprise level, and the AI Strategy Playbook shipped in 20+ languages. Today I write the documentation depth that powers tool agnostic AI knowledge management.", s: "10+ years experience" },
    curriculum: { t: "Curriculum & Learning Design", b: "Designed learning programs and curricula end to end: a leadership curriculum across seven partner universities, multi-month social emotional learning and leadership programs and retreat curricula for high school and college students, high ticket 1:1 men's work including course material, custom processing tools, and interaction cadences, the cohort and retreat programming I still run for men in their 20s, 30s, and 40s, a redesigned staff training program at a 1,500 person camp that lifted retention 67% year over year, and AI enablement content, guides, and quick reference materials for thousands of Fortune 500 users.", s: "7+ years experience" },
    global: { t: "Global & Cross-Cultural Work", b: "Led a team at Delta spanning eight countries and nine disciplines, a global journey mapping effort across North America, Europe, and Asia-Pacific, and AI enablement at Bayer delivered in 20+ languages from Indonesia to Brazil.", s: "7+ years experience" },
    /* -- AI & Emerging Technology -- */
    aiadoption: { t: "Tool and AI Adoption", b: "Adoption is a design problem. At Bayer, I took a Fortune 500's internal AI platform from 2% to 26% adoption in two months, by treating it as a competence problem rather than a trust problem. Beyond that, I developed an agentic persona service that multiple anti-AI teams started using daily, a project management system that construction field crews actually used on their phones, the migration of Bayer's global blueprint from Miro to TheyDo that matured design thinking across the enterprise through ease of discovery for customer journey maps, and currently lead teams from Notion, Dropbox, and Google Drive into tool agnostic markdown systems that increases their AI usage. This passion started in the film industry where I led the adoption of on-set and pre-production technologies across teams and departments.", s: "10+ years experience" },
    aitraining: { t: "Global AI Training", b: "Authored Bayer's AI Strategy Playbook and led its global dissemination in 20+ languages to thousands of internal users across business, engineering, design, and HR — training entire departments of the business from Indonesia to Brazil in a single quarter.", s: "3+ years experience" },
    aiagents: { t: "Building AI Agents", b: "Pioneered an agentic persona service at Bayer in 2023, before commercial agents were available. I built AI models of users our design team couldn't otherwise reach, wired into Microsoft Teams before commercial AI integrations existed for the company's stack. The workflow produced high fidelity user representations rapidly, validated by SMEs above 80% accuracy, and significantly reduced UAT failures across the teams that used them. That was over 3 years ago. Imagine what I can do with your data and Claude's newest features.", s: "3+ years experience" },
    agenticops: { t: "Agentic Operations Design", b: "Currently transforming business operations through agentic experience design alongside human and AI skill development, increasing the efficiency and accuracy of leaders, teams, and individual contributors. I own transformation engagements from scoping and discovery through implementation and adoption, and build AI-native, tool-agnostic knowledge management systems for creative and operational teams, architected for both human and agent ease of retrieval.", s: "3+ years experience" },
    responsibleai: { t: "Responsible AI", b: "I've been integrating AI into human systems since before commercial integrations existed — agentic personas validated by 20+ year subject-matter experts above 80% accuracy before teams were allowed to rely on them. I've also led stakeholder AI education from Indonesia to Brazil, and designed governance gates for agents to reduce failures and overstepping.", s: "3+ years experience" },
    aitooleval: { t: "AI Tool Evaluation", b: "Regularly self train on unfamiliar enterprise software to the depth of evaluating vendor fit, proven at the Fortune 500 level and across startups. Drove a Fortune 500's Customer Data Platform vendor selection and gave strategic input on its internal LLM platform build. My goal is to identify the right tool for the right job and the right persona.", s: "4+ years experience" },
    km: { t: "Knowledge Management", b: "Building knowledge management systems across multiple technologies and technological eras. My priority is KM for retrieval augmented AI. I design AI-native, tool-agnostic hubs and agentic decision-making systems architected for both human and agent ease of retrieval. I believe the next few years of tech growth will see knowledge management and access as the top priority. I have been developing AI enabled experiences on that assumption since 2023 at the Fortune 500 level.", s: "3+ years AI native experience" },
    aiproductstrategy: { t: "AI Product Strategy", b: "Led product strategy on the build out and adoption of Bayer's internal LLM platform pre-AI-boom, impacting design and product decisions and leading user testing. That work continues today as the core of my consulting practice. I build agentic, tool agnostic knowledge systems for creative and operational teams, design the prompt, workflow, and rule configurations they run on, and treat retrieval quality and human authored context as the leverage priority.", s: "3+ years experience" },
    aireliability: { t: "AI Reliability & Quality", b: "Build AI systems that perform reliably in production by treating the knowledge layer as the priority. SME written or validated content over endless prompt tuning, corpus audits for the percentage actually authored by humans, retrieval and validation management and measurement, and active guarding against the context dilution that comes from LLMs overwriting good context over time. Proven at the Fortune 500 level at Bayer, where agentic personas grounded on internal research and customer data were validated above 80% accuracy by subject matter experts with 20+ years in the field.", s: "3+ years experience" },
    rdlab: { t: "Personal R&D Lab", b: "My personal life is a constantly running R&D lab — I've been ramping on a new technology at least once a quarter since high school, and my current operating system pairs agentic AI workflows with a digital brain to extend what I can do. I love unfamiliar domains and emerging tech.", s: "16+ years experience" },
    /* -- Systems, Playbooks & Tools -- */
    playbooks: { t: "Playbook Writing", b: "Built an operations playbook at Campus Carriers that cut resource needs 60%, an entire startup playbook library that lifted efficiency 80% and removed the CEO from lower-level decisions at Dryland Revival, and a Fortune 500 AI strategy playbook shipped in 20+ languages at Bayer. This was all built on the foundation of playbook building for my teams in the film industry.", s: "10+ years experience" },
    pmsystems: { t: "PM System Design", b: "I have designed and facilitated project management systems my whole career. In film, I designed the project management system that managed hundreds of productions and kept projects on time and on budget while our crew averaged six productions at a time, peaking between ten and twelve. At Dryland, I designed the automations and information architecture end to end: built in ClickUp, rebuilt in Monday.com and run on Zapier automations. Prioritizing one click steps for every stakeholder in each process. At Bayer, I built out the scrum board and wrote all the stories for a legacy platform team that had no user stories or change tracking. Today I build project management systems in Notion and Claude for clients and my own operation.", s: "10+ years experience" },
    pmtools: { t: "PM Tool Fluency", b: "I've built project management systems end-to-end in ClickUp, Monday.com, Notion, Aha!, Motion, and Claude, and regularly self train on unfamiliar enterprise software to the depth of being able to evaluate vendor fit. Proven experience across startups, the entertainment industry, and the Fortune 500 level.", s: "13+ years experience" },
    tooling: { t: "Tooling & Platforms", b: "Fluent across the tech stack I have built and shipped projects in: design and mapping (Miro, Mural, TheyDo), knowledge and docs (Notion, Obsidian), project management (Monday.com, ClickUp, Asana, Jira, Aha!, Motion, Profit.co), AI (Claude Code, Claude Cowork, the Claude API, ChatGPT and the OpenAI API, agentic tooling), research and analytics (MAXQDA, DisplayR, QuestionPro), commerce (Shopify), and the everyday collaboration tools (Microsoft 365, Google Suite, Slack, Zoom, Loom, Dropbox). I self train on unfamiliar enterprise software to the depth of evaluating vendor fit at least once a quarter.", s: "16+ years experience" },
    toolmigration: { t: "Enterprise Tool Migration", b: "Led the migration of Bayer's global, enterprise level service blueprint from Miro to TheyDo — customer journey enablement at the enterprise level. I have also led multiple teams in migrating from Notion, Dropbox, Google Drive, and other knowledge sources to Obsidian via markdown strategy to become tool agnostic super users of their own information.", s: "4+ years experience" },
    /* -- Portfolio (public case studies) -- */
    portfolio: { t: "Full Portfolio", b: "Twelve public case studies across service blueprints, journey maps, systems maps, AI strategy, and UX — each one walks through the process, the deliverables, and the impact.", s: "<a href=\"https://www.hance.work/\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View at hance.work ↗</a>" },
    pfblueprintglobal: { t: "Global Enterprise Service Blueprint", b: "Bayer's 20,000+ point global service blueprint mapping tech, personas, and interactions across countries to surface redundancies and gaps.", s: "<a href=\"https://www.hance.work/Global-Enterprise-Level-Service-Blueprint-cd937db4cb344b318bae4c6d1e7ca9fa?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pfblueprintlocal: { t: "Local Enterprise Service Blueprint", b: "A focused enterprise service blueprint mapping a business's systems and interaction points end to end.", s: "<a href=\"https://www.hance.work/Local-Enterprise-Level-Service-Blueprint-74f9ecfa9f4a4873be1b909a7f5e37d8?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pfjourney: { t: "Global Journey Mapping Effort", b: "A 27-team global journey map producing 2,250 journey points and new processes on a confidential European compliance project.", s: "<a href=\"https://www.hance.work/Global-Journey-Mapping-Effort-228e643935ea43aab50ee95d8f56305f?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pferaf: { t: "Systems Flow (ERAF) Map", b: "A systems-flow map of 100+ interaction points that helped siloed teams see their role in the larger business — and kept employees who were ready to quit over 'bad communication.'", s: "<a href=\"https://www.hance.work/Systems-Flow-ERAF-Map-74cfa7e910564777a9883a55f066d4f9?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pfcdp: { t: "Customer Data Platform Roadmap", b: "The use cases and roadmap, built from the customer-experience perspective, that anchored a Fortune 500's Customer Data Platform vendor selection.", s: "<a href=\"https://www.hance.work/Customer-Data-Platform-Roadmap-0d65a3c99943497e9c969160e33742a2?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pfairoadmap: { t: "A.I. Product Roadmap", b: "Product roadmap for a Fortune 500's internal AI platform, defining the use cases and the path to adoption.", s: "<a href=\"https://www.hance.work/A-I-Product-Roadmap-d042f4d986e5441bbb80b5e5ea4bd018?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pfplatformplaybook: { t: "Platform Design Playbook", b: "A reusable playbook for designing and standing up new platforms.", s: "<a href=\"https://www.hance.work/Platform-Design-Playbook-838ea8da681f4577bce28f0ea7e30b67?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pfgenai: { t: "Generative A.I. Playbook", b: "The AI strategy playbook that drove adoption from 2% to 26%, shipped in 20+ languages to thousands of users.", s: "<a href=\"https://www.hance.work/Generative-A-I-Playbook-bb68ca8c80d840e5be083136a0b88f92?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pfpersonas: { t: "A.I. Persona Prototypes", b: "Agentic AI personas wired into Microsoft Teams — built before commercial AI integrations existed and launched across multiple company-wide platforms — so teams could interview user models they couldn't otherwise reach.", s: "<a href=\"https://www.hance.work/A-I-Persona-Prototypes-43575337f52c4cecaf4fdd871e5aa41e?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pfusertesting: { t: "User Testing Strategic Recommendations", b: "Using user research and testing to inform strategic product development on a supply chain platform.", s: "<a href=\"https://www.hance.work/User-Testing-Strategic-Recommendations-9f073d6ea0bb4bd1bef08d176895dd10?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pflegacyux: { t: "Legacy Software UX Strategy", b: "Restructured forms, progress indicators, and language to make a legacy platform more efficient and usable.", s: "<a href=\"https://www.hance.work/Legacy-Software-UX-Strategy-e189dab0fccc4d088f0f8e2a22b009a9?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
    pfprompt: { t: "Prompt Engineering Strategic Design", b: "A prompt engineering approach and template that let non-technical stakeholders across the company use generative AI effectively for the first time.", s: "<a href=\"https://www.hance.work/Prompt-Engineering-Strategic-Design-40891c882c00477e936743a5d0657ddc?pvs=25\" target=\"_blank\" rel=\"noopener\" style=\"color:inherit;text-decoration:underline\">View case study ↗</a>" },
  },
  categories: [
    {
      id: "people", name: "People Leadership", hue: "#f2a08a",
      skills: [
        ["Coaching", 3, ["coaching", "credentials"]],
        ["Mentoring", 3, ["mentorship", "talentdev"]],
        ["People Operations", 3, ["startupos", "hiring"]],
        ["Hiring", 3, ["hiring", "retention"]],
        ["Onboarding", 2, ["startupos", "hiring"]],
        ["Training", 2, ["trainingdesign", "curriculum"]],
        ["Organizational Design", 3, ["orgrestructuring", "startupos"]],
        ["Restructuring", 2, ["orgrestructuring", "workforce"]],
        ["Cultural Intelligence", 2, ["global", "psychology"]],
        ["Hiring Scorecard Design", 2, ["hiring"]],
        ["Performance Feedback Frameworks", 1, ["coaching"]],
        ["Conflict Mediation", 2, ["highstakesdecisions", "psychology"]],
        ["Organizational Change Management", 2, ["changemgmt", "orgrestructuring"]],
        ["Leadership Development", 3, ["coaching", "mentorship", "trainingdesign"]],
        ["Employee Retention", 3, ["retention", "trainingdesign"]],
        ["Talent Development", 2, ["talentdev", "mentorship"]],
        ["Recruiting / Talent Acquisition", 2, ["hiring"]],
        ["Interviewing & Candidate Assessment", 2, ["hiring"]],
        ["Team Building / Scaling", 2, ["startupos", "hiring"]],
        ["People Management", 2, ["crossfunctional", "cadences"]],
        ["Influence without Authority", 2, ["psychology", "execalign"]],
        ["Emotional Intelligence", 2, ["psychology", "coaching"]],
        ["Behavioral Psychology", 2, ["psychology"]],
        ["Strengths-Based Coaching", 2, ["coaching", "credentials"]],
        ["Social-Emotional Learning (SEL)", 2, ["curriculum", "coaching"]],
        ["Individual Development Plans (IDPs)", 2, ["talentdev"]],
        ["Workforce Planning", 2, ["workforce", "hiring"]],
        ["Change Management", 3, ["changemgmt", "aiadoption"]],
        ["Team Leadership", 2, ["crossfunctional", "servantleadership"]],
      ],
    },
    {
      id: "strategy", name: "Strategy & Business Design", hue: "#f2c26b",
      skills: [
        ["Strategic Visioning", 2, ["advising", "presentfuture"]],
        ["Roadmapping", 2, ["pmroadmap", "techstack"]],
        ["Operational Efficiency", 3, ["processopt", "resourcereduction"]],
        ["Stakeholder Management", 2, ["clientdelivery", "execalign"]],
        ["Consulting", 3, ["advising", "industries"]],
        ["Operating Model Design", 3, ["startupos", "bizmodel"]],
        ["Playbooks", 3, ["playbooks", "pfplatformplaybook"]],
        ["Business Model Design", 3, ["bizmodel", "gtm"]],
        ["Service Strategy", 2, ["blueprinting", "techstack"]],
        ["Product Strategy", 2, ["pmroadmap", "aiproductstrategy"]],
        ["Product Roadmaps", 2, ["pmroadmap", "pfairoadmap"]],
        ["Service Roadmaps", 2, ["techstack"]],
        ["Business Roadmaps", 2, ["gtm"]],
        ["Value Identification", 2, ["prioritization", "presentfuture"]],
        ["Go-to-Market Planning", 3, ["gtm", "revenue"]],
        ["Market Segmentation", 2, ["gtm"]],
        ["OKRs", 2, ["metricsdesign"]],
        ["KEIs", 1, ["metricsdesign"]],
        ["KPIs", 2, ["metricsdesign"]],
        ["Strategic Positioning", 2, ["gtm"]],
        ["Pattern Recognition", 2, ["systemsthinking", "domainlearning"]],
        ["Capability Mapping", 2, ["systemsmapping"]],
        ["RACI", 1, []],
        ["Scenario Planning", 2, ["financials"]],
        ["Facilitation", 3, ["facilitation"]],
        ["Vendor Selection", 3, ["vendorselection", "pfcdp"]],
        ["Tool & Technology Evaluation", 2, ["aitooleval", "vendorselection"]],
        ["Contract Scoping", 2, ["engagement"]],
        ["Statement of Work Writing", 1, ["engagement"]],
        ["Pricing Strategy", 2, ["gtm", "bizdev"]],
        ["Packaging Design", 2, ["gtm"]],
        ["Offer Design", 3, ["gtm", "bizdev"]],
        ["Organizational Maturity Assessment", 2, ["orgrestructuring"]],
        ["Business Development", 3, ["bizdev", "entrepreneurial"]],
        ["Strategic Recommendations", 2, ["techstack", "presentfuture"]],
        ["Business Transformation", 3, ["changemgmt", "orgrestructuring"]],
        ["Digital Transformation", 2, ["aiadoption", "toolmigration"]],
        ["Strategic Planning", 2, ["advising"]],
        ["Corporate Strategy", 1, ["execalign"]],
        ["Operational Excellence", 2, ["processopt"]],
        ["Process Improvement", 2, ["processopt", "playbooks"]],
        ["Process Optimization", 3, ["processopt", "resourcereduction"]],
        ["Continuous Improvement", 1, ["processopt"]],
        ["Business Operations", 2, ["startupos", "cadences"]],
        ["Strategy & Operations", 2, ["architectoperator"]],
        ["Innovation Frameworks", 2, ["decisionframeworks"]],
        ["Stakeholder Alignment", 2, ["execalign", "crossfunctional"]],
        ["Stakeholder Engagement", 2, ["execalign"]],
        ["Financial Modeling", 2, ["financials"]],
        ["Business Case Development", 2, ["bizmodel", "execalign"]],
        ["Feasibility Analysis", 2, ["advising", "constraints"]],
        ["Risk Identification", 2, ["riskflagging"]],
        ["Risk Mitigation", 2, ["riskflagging", "highstakesenv", "regulatory"]],
        ["Prioritization Frameworks", 2, ["prioritization", "decisionframeworks"]],
        ["Decision Frameworks", 3, ["decisionframeworks", "metricsdesign"]],
        ["Metrics Design", 3, ["metricsdesign"]],
        ["NPS", 2, ["metricsdesign"]],
        ["Client Relationship Management", 3, ["clientdelivery", "client13"]],
        ["Account Ownership", 2, ["engagement", "clientdelivery"]],
        ["Sustainability Strategy", 2, ["mission", "bizmodel"]],
      ],
    },
    {
      id: "service", name: "Service, Experience & Systems Design", hue: "#8ecdf0",
      skills: [
        ["Service Blueprinting", 3, ["blueprinting", "pfblueprintglobal", "pfblueprintlocal"]],
        ["Journey Mapping", 3, ["journeymapping", "pfjourney"]],
        ["Journey Management", 3, ["journeymgmt"]],
        ["Experience Management (XM)", 2, ["journeymgmt", "toolmigration"]],
        ["Experience Design", 3, ["xd"]],
        ["Solution Architecture", 2, ["ia", "techstack"]],
        ["Workshop Facilitation", 3, ["facilitation"]],
        ["UX Architecture", 2, ["productlead", "pflegacyux"]],
        ["Information Architecture", 3, ["ia"]],
        ["Design Sprint Facilitation", 2, ["facilitation"]],
        ["User Story Writing", 2, ["agile"]],
        ["Service Mapping", 2, ["systemsmapping", "blueprinting"]],
        ["Persona Design", 3, ["aiagents", "pfpersonas"]],
        ["Agentic Personas", 3, ["aiagents", "pfpersonas"]],
        ["Continuous Discovery", 2, ["research"]],
        ["Human Centered Design", 2, ["xd", "facilitation"]],
        ["Opportunity Solution Tree", 1, []],
        ["Jobs to be Done Framing", 1, []],
        ["Customer Journey", 2, ["journeymapping", "journeymgmt"]],
        ["Prototype Testing", 2, ["testing", "prototyping"]],
        ["Gap Identification", 2, ["blueprinting", "presentfuture"]],
        ["Service Design", 3, ["sd7", "blueprinting", "portfolio"]],
        ["Design Strategy", 2, ["designfluency", "designstandards"]],
        ["Prototyping", 3, ["prototyping"]],
        ["Customer Experience (CX) Strategy", 2, ["productlead", "xd"]],
        ["Systems Mapping", 3, ["systemsmapping", "pferaf"]],
        ["ERAF Mapping", 2, ["pferaf", "systemsmapping"]],
        ["Present State Mapping", 2, ["presentfuture"]],
        ["Future State Mapping", 2, ["presentfuture"]],
        ["Designing for Trust", 2, ["inherited", "aireliability"]],
        ["Design Standards", 2, ["designstandards"]],
        ["Tech Stack Blueprinting", 3, ["techstack"]],
        ["Tech Stack Assessment", 2, ["techstack", "aitooleval"]],
      ],
    },
    {
      id: "research", name: "Research & Discovery", hue: "#b5dd8a",
      skills: [
        ["User Research", 3, ["research", "researchtools"]],
        ["Stakeholder Interviews", 2, ["research", "orgrestructuring"]],
        ["Contextual Inquiry", 2, ["research", "researchtools"]],
        ["Synthesizing Research", 2, ["prioritization"]],
        ["Actionable Insights", 2, ["prioritization"]],
        ["Ethnographic Field Research", 3, ["research", "orgrestructuring"]],
        ["Product Discovery", 2, ["prioritization", "research"]],
        ["User Interviews", 2, ["research"]],
        ["Interview Design", 2, ["hiring"]],
        ["Research Design", 2, ["researchtools"]],
        ["Testing Design", 2, ["testing", "pfusertesting"]],
        ["AI for Research", 2, ["aiagents"]],
      ],
    },
    {
      id: "ai", name: "AI & Emerging Technology", hue: "#c7a6f2",
      skills: [
        ["Generative AI Strategy", 3, ["aiproductstrategy", "aitraining", "pfgenai"]],
        ["AI-Augmented Strategic Document Production", 2, ["strategicwriting", "km"]],
        ["AI-Augmented Design Thinking Workflows", 2, ["aiagents"]],
        ["Synthetic Users", 3, ["aiagents", "pfpersonas"]],
        ["Virtual Personas", 2, ["aiagents", "pfpersonas"]],
        ["AI Implementation Strategy", 2, ["aiadoption", "aireliability"]],
        ["Prompt Engineering", 3, ["pfprompt", "aiproductstrategy"]],
        ["Custom GPTs", 2, ["aiagents"]],
        ["Custom GPT Development & Deployment", 2, ["aiagents"]],
        ["AI-Augmented Operating Workflows", 2, ["agenticops", "rdlab"]],
        ["AI Evangelism", 2, ["aitraining", "aiadoption"]],
        ["Stakeholder Education", 2, ["aitraining"]],
        ["LLM Workflow Orchestration", 2, ["agenticops", "km"]],
        ["Agentic Design", 3, ["aiagents", "agenticops"]],
        ["Agent Design", 2, ["aiagents"]],
        ["Retrieval Augmented Generation Literacy", 2, ["km", "aireliability"]],
        ["Prompt Design", 2, ["pfprompt"]],
        ["Digital Change Management", 2, ["aiadoption", "toolmigration"]],
        ["AI Adoption", 3, ["aiadoption", "pfgenai"]],
        ["AI Ethics", 2, ["responsibleai"]],
        ["Responsible AI", 2, ["responsibleai"]],
        ["AI Transformation", 2, ["agenticops", "aiadoption"]],
        ["AI Enablement", 3, ["aitraining", "aiadoption"]],
        ["AI Upskilling & Training", 2, ["aitraining"]],
        ["Adoption Measurement", 2, ["metricsdesign", "aiadoption"]],
        ["Adoption Metrics", 2, ["metricsdesign", "aiadoption"]],
      ],
    },
    {
      id: "ops", name: "Operations & Delivery", hue: "#7fdec2",
      skills: [
        ["System Architecture", 2, ["ia", "pmsystems"]],
        ["Knowledge Management Architecture", 3, ["km"]],
        ["Resource Management", 2, ["resourcereduction", "financials"]],
        ["Cross-Functional Collaboration", 2, ["crossfunctional", "crossdiscipline"]],
        ["Cross-Functional Facilitation", 2, ["facilitation", "crossfunctional"]],
        ["Cross-Cultural Facilitation", 2, ["global"]],
        ["Customer Data Platforms", 2, ["vendorselection", "pfcdp"]],
        ["Program Management", 2, ["concurrent", "workstreams"]],
        ["Project Management", 3, ["pmroadmap", "concurrent", "parallel"]],
        ["Cross-Functional Leadership", 3, ["crossfunctional"]],
        ["Implementation Planning", 2, ["architectoperator"]],
        ["Workflow Automation", 2, ["pmsystems", "agenticops"]],
        ["Budget Management", 2, ["financials"]],
        ["Product Delivery", 2, ["productlead", "agile"]],
        ["Vendor Management", 2, ["vendorselection", "clientdelivery"]],
        ["Compliance Management", 2, ["regulatory"]],
        ["Live Event Operations", 3, ["liveevents"]],
        ["Logistics Management", 2, ["startupos", "architectoperator"]],
        ["Field Operations", 2, ["startupos", "changemgmt"]],
        ["Enterprise Tool Migration", 2, ["toolmigration"]],
        ["Production Management", 3, ["concurrent", "highstakesdecisions", "liveevents"]],
      ],
    },
    {
      id: "comms", name: "Communication & Writing", hue: "#f2aed0",
      skills: [
        ["Strategic Documentation", 3, ["strategicwriting", "playbooks"]],
        ["Storytelling for Business Audiences", 2, ["storytelling"]],
        ["Executive Communications", 2, ["execalign", "storytelling"]],
        ["Advising", 3, ["advising"]],
        ["Translating between Engineering / Design / Business", 3, ["crossdiscipline"]],
        ["Instructional Design", 2, ["trainingdesign", "curriculum"]],
        ["Learning Experience Design", 2, ["curriculum"]],
        ["Curriculum Design", 3, ["curriculum", "trainingdesign"]],
        ["Workshop Design", 2, ["facilitation", "curriculum"]],
        ["Pitching", 2, ["storytelling", "execalign"]],
        ["Presenting", 2, ["speaking"]],
        ["UX Writing", 2, ["pflegacyux"]],
        ["Strategic Narrative Writing", 2, ["storytelling", "strategicwriting"]],
        ["Long Form Essay Writing", 2, ["strategicwriting"]],
        ["Public Speaking", 3, ["speaking"]],
        ["Workshop Hosting", 2, ["facilitation"]],
      ],
    },
    {
      id: "methods", name: "Methodologies & Frameworks", hue: "#a7b6f2",
      skills: [
        ["Agile Methodology", 2, ["agile"]],
        ["Lean Methodology", 1, []],
        ["Sprint Planning", 2, ["agile", "cadences"]],
        ["Story Refinement", 2, ["agile"]],
        ["Backlog Refinement", 2, ["agile", "pmroadmap"]],
        ["UAT (User Acceptance Testing)", 3, ["testing", "productlead"]],
        ["A/B Testing", 1, []],
        ["Usability Testing", 2, ["testing", "pfusertesting"]],
        ["Design Thinking", 3, ["facilitation", "ma"]],
        ["Systems Thinking", 3, ["systemsthinking", "systemsmapping", "rootcause"]],
        ["Lateral Thinking", 1, []],
        ["Abductive Reasoning", 1, []],
        ["Root Cause Thinking", 3, ["rootcause"]],
        ["Structured Problem Solving", 2, ["decisionframeworks", "rootcause"]],
        ["Self-Determination Theory", 2, ["trainingdesign"]],
        ["Business Model Canvas", 2, ["prioritization"]],
        ["MVP Design", 2, ["prototyping", "gtm"]],
        ["Rapid Concept Validation", 2, ["prototyping", "testing"]],
        ["Lean Canvas", 1, []],
      ],
    },
    {
      id: "tech", name: "Tools & Technology", hue: "#c9d2dc",
      skills: [
        ["Miro", 3, ["facilitation", "toolmigration"]],
        ["TheyDo", 2, ["toolmigration", "journeymgmt"]],
        ["Notion", 2, ["pmtools", "toolmigration"]],
        ["Motion", 2, ["pmtools"]],
        ["Claude Code", 2, ["tooling", "km"]],
        ["Claude Cowork", 2, ["tooling"]],
        ["Claude API", 1, ["tooling"]],
        ["Agentic AI Tools", 3, ["aiagents", "agenticops"]],
        ["ChatGPT / OpenAI API", 1, ["tooling"]],
        ["Obsidian", 2, ["km", "toolmigration"]],
        ["Mural", 1, ["tooling"]],
        ["Monday", 2, ["pmsystems"]],
        ["Slack", 1, ["tooling"]],
        ["Zoom", 1, ["tooling"]],
        ["Microsoft 365", 2, ["tooling", "aiagents"]],
        ["Google Suite", 1, ["tooling"]],
        ["Dropbox", 1, ["tooling"]],
        ["Aha!", 2, ["pmtools"]],
        ["Loom", 1, ["tooling"]],
        ["Asana", 1, ["tooling"]],
        ["ClickUp", 2, ["pmsystems", "pmtools"]],
        ["Jira", 1, ["tooling"]],
        ["Profit.co", 1, ["tooling"]],
        ["Shopify", 1, ["tooling"]],
        ["MAXQDA", 2, ["researchtools"]],
        ["DisplayR", 2, ["researchtools"]],
        ["QuestionPro", 2, ["researchtools"]],
        ["Zapier", 2, ["pmsystems", "techstack"]],
      ],
    },
  ],
};
